/*
 * LUSID API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.lusid.model;

import java.util.Objects;
import com.finbourne.lusid.model.GroupReconciliationComparisonRuleStringValueMap;
import com.finbourne.lusid.model.GroupReconciliationCoreComparisonRuleOperand;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.lusid.JSON;

/**
 * GroupReconciliationCoreAttributeRule
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class GroupReconciliationCoreAttributeRule {
  public static final String SERIALIZED_NAME_LEFT = "left";
  @SerializedName(SERIALIZED_NAME_LEFT)
  private GroupReconciliationCoreComparisonRuleOperand left;

  public static final String SERIALIZED_NAME_RIGHT = "right";
  @SerializedName(SERIALIZED_NAME_RIGHT)
  private GroupReconciliationCoreComparisonRuleOperand right;

  public static final String SERIALIZED_NAME_ALLOWABLE_STRING_MAPPINGS = "allowableStringMappings";
  @SerializedName(SERIALIZED_NAME_ALLOWABLE_STRING_MAPPINGS)
  private List<GroupReconciliationComparisonRuleStringValueMap> allowableStringMappings;

  public static final String SERIALIZED_NAME_IS_COMPARISON_CASE_SENSITIVE = "isComparisonCaseSensitive";
  @SerializedName(SERIALIZED_NAME_IS_COMPARISON_CASE_SENSITIVE)
  private Boolean isComparisonCaseSensitive;

  public GroupReconciliationCoreAttributeRule() {
  }

  public GroupReconciliationCoreAttributeRule left(GroupReconciliationCoreComparisonRuleOperand left) {
    
    this.left = left;
    return this;
  }

   /**
   * Get left
   * @return left
  **/
  @jakarta.annotation.Nonnull
  public GroupReconciliationCoreComparisonRuleOperand getLeft() {
    return left;
  }


  public void setLeft(GroupReconciliationCoreComparisonRuleOperand left) {
    this.left = left;
  }


  public GroupReconciliationCoreAttributeRule right(GroupReconciliationCoreComparisonRuleOperand right) {
    
    this.right = right;
    return this;
  }

   /**
   * Get right
   * @return right
  **/
  @jakarta.annotation.Nonnull
  public GroupReconciliationCoreComparisonRuleOperand getRight() {
    return right;
  }


  public void setRight(GroupReconciliationCoreComparisonRuleOperand right) {
    this.right = right;
  }


  public GroupReconciliationCoreAttributeRule allowableStringMappings(List<GroupReconciliationComparisonRuleStringValueMap> allowableStringMappings) {
    
    this.allowableStringMappings = allowableStringMappings;
    return this;
  }

  public GroupReconciliationCoreAttributeRule addAllowableStringMappingsItem(GroupReconciliationComparisonRuleStringValueMap allowableStringMappingsItem) {
    if (this.allowableStringMappings == null) {
      this.allowableStringMappings = new ArrayList<>();
    }
    this.allowableStringMappings.add(allowableStringMappingsItem);
    return this;
  }

   /**
   * The string mappings to use when comparing
   * @return allowableStringMappings
  **/
  @jakarta.annotation.Nullable
  public List<GroupReconciliationComparisonRuleStringValueMap> getAllowableStringMappings() {
    return allowableStringMappings;
  }


  public void setAllowableStringMappings(List<GroupReconciliationComparisonRuleStringValueMap> allowableStringMappings) {
    this.allowableStringMappings = allowableStringMappings;
  }


  public GroupReconciliationCoreAttributeRule isComparisonCaseSensitive(Boolean isComparisonCaseSensitive) {
    
    this.isComparisonCaseSensitive = isComparisonCaseSensitive;
    return this;
  }

   /**
   * Whether the compare keys and strings mappings case sensitive or not
   * @return isComparisonCaseSensitive
  **/
  @jakarta.annotation.Nonnull
  public Boolean getIsComparisonCaseSensitive() {
    return isComparisonCaseSensitive;
  }


  public void setIsComparisonCaseSensitive(Boolean isComparisonCaseSensitive) {
    this.isComparisonCaseSensitive = isComparisonCaseSensitive;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GroupReconciliationCoreAttributeRule groupReconciliationCoreAttributeRule = (GroupReconciliationCoreAttributeRule) o;
    return Objects.equals(this.left, groupReconciliationCoreAttributeRule.left) &&
        Objects.equals(this.right, groupReconciliationCoreAttributeRule.right) &&
        Objects.equals(this.allowableStringMappings, groupReconciliationCoreAttributeRule.allowableStringMappings) &&
        Objects.equals(this.isComparisonCaseSensitive, groupReconciliationCoreAttributeRule.isComparisonCaseSensitive);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(left, right, allowableStringMappings, isComparisonCaseSensitive);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GroupReconciliationCoreAttributeRule {\n");
    sb.append("    left: ").append(toIndentedString(left)).append("\n");
    sb.append("    right: ").append(toIndentedString(right)).append("\n");
    sb.append("    allowableStringMappings: ").append(toIndentedString(allowableStringMappings)).append("\n");
    sb.append("    isComparisonCaseSensitive: ").append(toIndentedString(isComparisonCaseSensitive)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("left");
    openapiFields.add("right");
    openapiFields.add("allowableStringMappings");
    openapiFields.add("isComparisonCaseSensitive");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("left");
    openapiRequiredFields.add("right");
    openapiRequiredFields.add("isComparisonCaseSensitive");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to GroupReconciliationCoreAttributeRule
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GroupReconciliationCoreAttributeRule.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GroupReconciliationCoreAttributeRule is not found in the empty JSON string", GroupReconciliationCoreAttributeRule.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : GroupReconciliationCoreAttributeRule.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `left`
      GroupReconciliationCoreComparisonRuleOperand.validateJsonElement(jsonObj.get("left"));
      // validate the required field `right`
      GroupReconciliationCoreComparisonRuleOperand.validateJsonElement(jsonObj.get("right"));
      if (jsonObj.get("allowableStringMappings") != null && !jsonObj.get("allowableStringMappings").isJsonNull()) {
        JsonArray jsonArrayallowableStringMappings = jsonObj.getAsJsonArray("allowableStringMappings");
        if (jsonArrayallowableStringMappings != null) {
          // ensure the json data is an array
          if (!jsonObj.get("allowableStringMappings").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `allowableStringMappings` to be an array in the JSON string but got `%s`", jsonObj.get("allowableStringMappings").toString()));
          }

          // validate the optional field `allowableStringMappings` (array)
          for (int i = 0; i < jsonArrayallowableStringMappings.size(); i++) {
            GroupReconciliationComparisonRuleStringValueMap.validateJsonElement(jsonArrayallowableStringMappings.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GroupReconciliationCoreAttributeRule.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GroupReconciliationCoreAttributeRule' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GroupReconciliationCoreAttributeRule> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GroupReconciliationCoreAttributeRule.class));

       return (TypeAdapter<T>) new TypeAdapter<GroupReconciliationCoreAttributeRule>() {
           @Override
           public void write(JsonWriter out, GroupReconciliationCoreAttributeRule value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GroupReconciliationCoreAttributeRule read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of GroupReconciliationCoreAttributeRule given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of GroupReconciliationCoreAttributeRule
  * @throws IOException if the JSON string is invalid with respect to GroupReconciliationCoreAttributeRule
  */
  public static GroupReconciliationCoreAttributeRule fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GroupReconciliationCoreAttributeRule.class);
  }

 /**
  * Convert an instance of GroupReconciliationCoreAttributeRule to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
