/*
 * LUSID API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.lusid.model;

import java.util.Objects;
import com.finbourne.lusid.model.Instrument;
import com.finbourne.lusid.model.Link;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.lusid.JSON;

/**
 * A list of instruments.
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class InstrumentEntity {
  public static final String SERIALIZED_NAME_HREF = "href";
  @SerializedName(SERIALIZED_NAME_HREF)
  private URI href;

  public static final String SERIALIZED_NAME_ENTITY_UNIQUE_ID = "entityUniqueId";
  @SerializedName(SERIALIZED_NAME_ENTITY_UNIQUE_ID)
  private String entityUniqueId;

  public static final String SERIALIZED_NAME_AS_AT_VERSION_NUMBER = "asAtVersionNumber";
  @SerializedName(SERIALIZED_NAME_AS_AT_VERSION_NUMBER)
  private Integer asAtVersionNumber;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_AS_AT_DELETED = "asAtDeleted";
  @SerializedName(SERIALIZED_NAME_AS_AT_DELETED)
  private OffsetDateTime asAtDeleted;

  public static final String SERIALIZED_NAME_USER_ID_DELETED = "userIdDeleted";
  @SerializedName(SERIALIZED_NAME_USER_ID_DELETED)
  private String userIdDeleted;

  public static final String SERIALIZED_NAME_REQUEST_ID_DELETED = "requestIdDeleted";
  @SerializedName(SERIALIZED_NAME_REQUEST_ID_DELETED)
  private String requestIdDeleted;

  public static final String SERIALIZED_NAME_EFFECTIVE_AT_CREATED = "effectiveAtCreated";
  @SerializedName(SERIALIZED_NAME_EFFECTIVE_AT_CREATED)
  private OffsetDateTime effectiveAtCreated;

  public static final String SERIALIZED_NAME_PREVAILING_INSTRUMENT = "prevailingInstrument";
  @SerializedName(SERIALIZED_NAME_PREVAILING_INSTRUMENT)
  private Instrument prevailingInstrument;

  public static final String SERIALIZED_NAME_DELETED_INSTRUMENT = "deletedInstrument";
  @SerializedName(SERIALIZED_NAME_DELETED_INSTRUMENT)
  private Instrument deletedInstrument;

  public static final String SERIALIZED_NAME_PREVIEWED_STATUS = "previewedStatus";
  @SerializedName(SERIALIZED_NAME_PREVIEWED_STATUS)
  private String previewedStatus;

  public static final String SERIALIZED_NAME_PREVIEWED_INSTRUMENT = "previewedInstrument";
  @SerializedName(SERIALIZED_NAME_PREVIEWED_INSTRUMENT)
  private Instrument previewedInstrument;

  public static final String SERIALIZED_NAME_LINKS = "links";
  @SerializedName(SERIALIZED_NAME_LINKS)
  private List<Link> links;

  public InstrumentEntity() {
  }

  public InstrumentEntity href(URI href) {
    
    this.href = href;
    return this;
  }

   /**
   * The specific Uniform Resource Identifier (URI) for this resource at the requested effective and asAt datetime.
   * @return href
  **/
  @jakarta.annotation.Nonnull
  public URI getHref() {
    return href;
  }


  public void setHref(URI href) {
    this.href = href;
  }


  public InstrumentEntity entityUniqueId(String entityUniqueId) {
    
    this.entityUniqueId = entityUniqueId;
    return this;
  }

   /**
   * The unique id of the entity.
   * @return entityUniqueId
  **/
  @jakarta.annotation.Nonnull
  public String getEntityUniqueId() {
    return entityUniqueId;
  }


  public void setEntityUniqueId(String entityUniqueId) {
    this.entityUniqueId = entityUniqueId;
  }


  public InstrumentEntity asAtVersionNumber(Integer asAtVersionNumber) {
    
    this.asAtVersionNumber = asAtVersionNumber;
    return this;
  }

   /**
   * The integer version number for the entity (the entity was created at version 1)
   * @return asAtVersionNumber
  **/
  @jakarta.annotation.Nullable
  public Integer getAsAtVersionNumber() {
    return asAtVersionNumber;
  }


  public void setAsAtVersionNumber(Integer asAtVersionNumber) {
    this.asAtVersionNumber = asAtVersionNumber;
  }


  public InstrumentEntity status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * The status of the entity at the current time.
   * @return status
  **/
  @jakarta.annotation.Nonnull
  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    this.status = status;
  }


  public InstrumentEntity asAtDeleted(OffsetDateTime asAtDeleted) {
    
    this.asAtDeleted = asAtDeleted;
    return this;
  }

   /**
   * The asAt datetime at which the entity was deleted.
   * @return asAtDeleted
  **/
  @jakarta.annotation.Nullable
  public OffsetDateTime getAsAtDeleted() {
    return asAtDeleted;
  }


  public void setAsAtDeleted(OffsetDateTime asAtDeleted) {
    this.asAtDeleted = asAtDeleted;
  }


  public InstrumentEntity userIdDeleted(String userIdDeleted) {
    
    this.userIdDeleted = userIdDeleted;
    return this;
  }

   /**
   * The unique id of the user who deleted the entity.
   * @return userIdDeleted
  **/
  @jakarta.annotation.Nullable
  public String getUserIdDeleted() {
    return userIdDeleted;
  }


  public void setUserIdDeleted(String userIdDeleted) {
    this.userIdDeleted = userIdDeleted;
  }


  public InstrumentEntity requestIdDeleted(String requestIdDeleted) {
    
    this.requestIdDeleted = requestIdDeleted;
    return this;
  }

   /**
   * The unique request id of the command that deleted the entity.
   * @return requestIdDeleted
  **/
  @jakarta.annotation.Nullable
  public String getRequestIdDeleted() {
    return requestIdDeleted;
  }


  public void setRequestIdDeleted(String requestIdDeleted) {
    this.requestIdDeleted = requestIdDeleted;
  }


  public InstrumentEntity effectiveAtCreated(OffsetDateTime effectiveAtCreated) {
    
    this.effectiveAtCreated = effectiveAtCreated;
    return this;
  }

   /**
   * The EffectiveAt this Entity is created, if entity does not currently exist in EffectiveAt.
   * @return effectiveAtCreated
  **/
  @jakarta.annotation.Nullable
  public OffsetDateTime getEffectiveAtCreated() {
    return effectiveAtCreated;
  }


  public void setEffectiveAtCreated(OffsetDateTime effectiveAtCreated) {
    this.effectiveAtCreated = effectiveAtCreated;
  }


  public InstrumentEntity prevailingInstrument(Instrument prevailingInstrument) {
    
    this.prevailingInstrument = prevailingInstrument;
    return this;
  }

   /**
   * Get prevailingInstrument
   * @return prevailingInstrument
  **/
  @jakarta.annotation.Nullable
  public Instrument getPrevailingInstrument() {
    return prevailingInstrument;
  }


  public void setPrevailingInstrument(Instrument prevailingInstrument) {
    this.prevailingInstrument = prevailingInstrument;
  }


  public InstrumentEntity deletedInstrument(Instrument deletedInstrument) {
    
    this.deletedInstrument = deletedInstrument;
    return this;
  }

   /**
   * Get deletedInstrument
   * @return deletedInstrument
  **/
  @jakarta.annotation.Nullable
  public Instrument getDeletedInstrument() {
    return deletedInstrument;
  }


  public void setDeletedInstrument(Instrument deletedInstrument) {
    this.deletedInstrument = deletedInstrument;
  }


  public InstrumentEntity previewedStatus(String previewedStatus) {
    
    this.previewedStatus = previewedStatus;
    return this;
  }

   /**
   * The status of the previewed entity.
   * @return previewedStatus
  **/
  @jakarta.annotation.Nullable
  public String getPreviewedStatus() {
    return previewedStatus;
  }


  public void setPreviewedStatus(String previewedStatus) {
    this.previewedStatus = previewedStatus;
  }


  public InstrumentEntity previewedInstrument(Instrument previewedInstrument) {
    
    this.previewedInstrument = previewedInstrument;
    return this;
  }

   /**
   * Get previewedInstrument
   * @return previewedInstrument
  **/
  @jakarta.annotation.Nullable
  public Instrument getPreviewedInstrument() {
    return previewedInstrument;
  }


  public void setPreviewedInstrument(Instrument previewedInstrument) {
    this.previewedInstrument = previewedInstrument;
  }


  public InstrumentEntity links(List<Link> links) {
    
    this.links = links;
    return this;
  }

  public InstrumentEntity addLinksItem(Link linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<>();
    }
    this.links.add(linksItem);
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @jakarta.annotation.Nullable
  public List<Link> getLinks() {
    return links;
  }


  public void setLinks(List<Link> links) {
    this.links = links;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InstrumentEntity instrumentEntity = (InstrumentEntity) o;
    return Objects.equals(this.href, instrumentEntity.href) &&
        Objects.equals(this.entityUniqueId, instrumentEntity.entityUniqueId) &&
        Objects.equals(this.asAtVersionNumber, instrumentEntity.asAtVersionNumber) &&
        Objects.equals(this.status, instrumentEntity.status) &&
        Objects.equals(this.asAtDeleted, instrumentEntity.asAtDeleted) &&
        Objects.equals(this.userIdDeleted, instrumentEntity.userIdDeleted) &&
        Objects.equals(this.requestIdDeleted, instrumentEntity.requestIdDeleted) &&
        Objects.equals(this.effectiveAtCreated, instrumentEntity.effectiveAtCreated) &&
        Objects.equals(this.prevailingInstrument, instrumentEntity.prevailingInstrument) &&
        Objects.equals(this.deletedInstrument, instrumentEntity.deletedInstrument) &&
        Objects.equals(this.previewedStatus, instrumentEntity.previewedStatus) &&
        Objects.equals(this.previewedInstrument, instrumentEntity.previewedInstrument) &&
        Objects.equals(this.links, instrumentEntity.links);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(href, entityUniqueId, asAtVersionNumber, status, asAtDeleted, userIdDeleted, requestIdDeleted, effectiveAtCreated, prevailingInstrument, deletedInstrument, previewedStatus, previewedInstrument, links);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InstrumentEntity {\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    entityUniqueId: ").append(toIndentedString(entityUniqueId)).append("\n");
    sb.append("    asAtVersionNumber: ").append(toIndentedString(asAtVersionNumber)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    asAtDeleted: ").append(toIndentedString(asAtDeleted)).append("\n");
    sb.append("    userIdDeleted: ").append(toIndentedString(userIdDeleted)).append("\n");
    sb.append("    requestIdDeleted: ").append(toIndentedString(requestIdDeleted)).append("\n");
    sb.append("    effectiveAtCreated: ").append(toIndentedString(effectiveAtCreated)).append("\n");
    sb.append("    prevailingInstrument: ").append(toIndentedString(prevailingInstrument)).append("\n");
    sb.append("    deletedInstrument: ").append(toIndentedString(deletedInstrument)).append("\n");
    sb.append("    previewedStatus: ").append(toIndentedString(previewedStatus)).append("\n");
    sb.append("    previewedInstrument: ").append(toIndentedString(previewedInstrument)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("href");
    openapiFields.add("entityUniqueId");
    openapiFields.add("asAtVersionNumber");
    openapiFields.add("status");
    openapiFields.add("asAtDeleted");
    openapiFields.add("userIdDeleted");
    openapiFields.add("requestIdDeleted");
    openapiFields.add("effectiveAtCreated");
    openapiFields.add("prevailingInstrument");
    openapiFields.add("deletedInstrument");
    openapiFields.add("previewedStatus");
    openapiFields.add("previewedInstrument");
    openapiFields.add("links");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("href");
    openapiRequiredFields.add("entityUniqueId");
    openapiRequiredFields.add("status");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to InstrumentEntity
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!InstrumentEntity.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in InstrumentEntity is not found in the empty JSON string", InstrumentEntity.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : InstrumentEntity.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("href").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `href` to be a primitive type in the JSON string but got `%s`", jsonObj.get("href").toString()));
      }
      if (!jsonObj.get("entityUniqueId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `entityUniqueId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("entityUniqueId").toString()));
      }
      if (!jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      if ((jsonObj.get("userIdDeleted") != null && !jsonObj.get("userIdDeleted").isJsonNull()) && !jsonObj.get("userIdDeleted").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `userIdDeleted` to be a primitive type in the JSON string but got `%s`", jsonObj.get("userIdDeleted").toString()));
      }
      if ((jsonObj.get("requestIdDeleted") != null && !jsonObj.get("requestIdDeleted").isJsonNull()) && !jsonObj.get("requestIdDeleted").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `requestIdDeleted` to be a primitive type in the JSON string but got `%s`", jsonObj.get("requestIdDeleted").toString()));
      }
      // validate the optional field `prevailingInstrument`
      if (jsonObj.get("prevailingInstrument") != null && !jsonObj.get("prevailingInstrument").isJsonNull()) {
        Instrument.validateJsonElement(jsonObj.get("prevailingInstrument"));
      }
      // validate the optional field `deletedInstrument`
      if (jsonObj.get("deletedInstrument") != null && !jsonObj.get("deletedInstrument").isJsonNull()) {
        Instrument.validateJsonElement(jsonObj.get("deletedInstrument"));
      }
      if ((jsonObj.get("previewedStatus") != null && !jsonObj.get("previewedStatus").isJsonNull()) && !jsonObj.get("previewedStatus").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `previewedStatus` to be a primitive type in the JSON string but got `%s`", jsonObj.get("previewedStatus").toString()));
      }
      // validate the optional field `previewedInstrument`
      if (jsonObj.get("previewedInstrument") != null && !jsonObj.get("previewedInstrument").isJsonNull()) {
        Instrument.validateJsonElement(jsonObj.get("previewedInstrument"));
      }
      if (jsonObj.get("links") != null && !jsonObj.get("links").isJsonNull()) {
        JsonArray jsonArraylinks = jsonObj.getAsJsonArray("links");
        if (jsonArraylinks != null) {
          // ensure the json data is an array
          if (!jsonObj.get("links").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `links` to be an array in the JSON string but got `%s`", jsonObj.get("links").toString()));
          }

          // validate the optional field `links` (array)
          for (int i = 0; i < jsonArraylinks.size(); i++) {
            Link.validateJsonElement(jsonArraylinks.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!InstrumentEntity.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'InstrumentEntity' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<InstrumentEntity> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(InstrumentEntity.class));

       return (TypeAdapter<T>) new TypeAdapter<InstrumentEntity>() {
           @Override
           public void write(JsonWriter out, InstrumentEntity value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public InstrumentEntity read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of InstrumentEntity given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of InstrumentEntity
  * @throws IOException if the JSON string is invalid with respect to InstrumentEntity
  */
  public static InstrumentEntity fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, InstrumentEntity.class);
  }

 /**
  * Convert an instance of InstrumentEntity to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
