/*
 * LUSID API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.lusid.model;

import java.util.Objects;
import com.finbourne.lusid.model.AggregateMatchingRule;
import com.finbourne.lusid.model.CoreMatchingRule;
import com.finbourne.lusid.model.GroupReconciliationFilters;
import com.finbourne.lusid.model.Link;
import com.finbourne.lusid.model.RecDatasetSchemas;
import com.finbourne.lusid.model.ResourceId;
import com.finbourne.lusid.model.SupplementalAttribute;
import com.finbourne.lusid.model.ToleranceBase;
import com.finbourne.lusid.model.Version;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.lusid.JSON;

/**
 * MatchingRuleset
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class MatchingRuleset {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private ResourceId id;

  public static final String SERIALIZED_NAME_DISPLAY_NAME = "displayName";
  @SerializedName(SERIALIZED_NAME_DISPLAY_NAME)
  private String displayName;

  public static final String SERIALIZED_NAME_REC_TYPE = "recType";
  @SerializedName(SERIALIZED_NAME_REC_TYPE)
  private String recType;

  public static final String SERIALIZED_NAME_DATASET_SCHEMAS = "datasetSchemas";
  @SerializedName(SERIALIZED_NAME_DATASET_SCHEMAS)
  private RecDatasetSchemas datasetSchemas;

  public static final String SERIALIZED_NAME_FILTERS = "filters";
  @SerializedName(SERIALIZED_NAME_FILTERS)
  private GroupReconciliationFilters filters;

  public static final String SERIALIZED_NAME_CORE_RULES = "coreRules";
  @SerializedName(SERIALIZED_NAME_CORE_RULES)
  private List<CoreMatchingRule> coreRules = new ArrayList<>();

  public static final String SERIALIZED_NAME_AGGREGATE_RULES = "aggregateRules";
  @SerializedName(SERIALIZED_NAME_AGGREGATE_RULES)
  private List<AggregateMatchingRule> aggregateRules = new ArrayList<>();

  public static final String SERIALIZED_NAME_CORE_TOLERANCES = "coreTolerances";
  @SerializedName(SERIALIZED_NAME_CORE_TOLERANCES)
  private List<ToleranceBase> coreTolerances;

  public static final String SERIALIZED_NAME_AGGREGATE_TOLERANCES = "aggregateTolerances";
  @SerializedName(SERIALIZED_NAME_AGGREGATE_TOLERANCES)
  private List<ToleranceBase> aggregateTolerances;

  public static final String SERIALIZED_NAME_ALLOW_PARTIAL_MATCHING = "allowPartialMatching";
  @SerializedName(SERIALIZED_NAME_ALLOW_PARTIAL_MATCHING)
  private Boolean allowPartialMatching;

  public static final String SERIALIZED_NAME_SUPPLEMENTAL_ATTRIBUTES = "supplementalAttributes";
  @SerializedName(SERIALIZED_NAME_SUPPLEMENTAL_ATTRIBUTES)
  private List<SupplementalAttribute> supplementalAttributes;

  public static final String SERIALIZED_NAME_HREF = "href";
  @SerializedName(SERIALIZED_NAME_HREF)
  private URI href;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  private Version version;

  public static final String SERIALIZED_NAME_LINKS = "links";
  @SerializedName(SERIALIZED_NAME_LINKS)
  private List<Link> links;

  public MatchingRuleset() {
  }

  public MatchingRuleset id(ResourceId id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @jakarta.annotation.Nonnull
  public ResourceId getId() {
    return id;
  }


  public void setId(ResourceId id) {
    this.id = id;
  }


  public MatchingRuleset displayName(String displayName) {
    
    this.displayName = displayName;
    return this;
  }

   /**
   * The name of the matching ruleset.
   * @return displayName
  **/
  @jakarta.annotation.Nonnull
  public String getDisplayName() {
    return displayName;
  }


  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }


  public MatchingRuleset recType(String recType) {
    
    this.recType = recType;
    return this;
  }

   /**
   * The type of reconciliation to perform. Available values: Holding, CashHolding, Valuation, InputTransaction, OutputTransaction, SettlementActivity.
   * @return recType
  **/
  @jakarta.annotation.Nonnull
  public String getRecType() {
    return recType;
  }


  public void setRecType(String recType) {
    this.recType = recType;
  }


  public MatchingRuleset datasetSchemas(RecDatasetSchemas datasetSchemas) {
    
    this.datasetSchemas = datasetSchemas;
    return this;
  }

   /**
   * Get datasetSchemas
   * @return datasetSchemas
  **/
  @jakarta.annotation.Nonnull
  public RecDatasetSchemas getDatasetSchemas() {
    return datasetSchemas;
  }


  public void setDatasetSchemas(RecDatasetSchemas datasetSchemas) {
    this.datasetSchemas = datasetSchemas;
  }


  public MatchingRuleset filters(GroupReconciliationFilters filters) {
    
    this.filters = filters;
    return this;
  }

   /**
   * Get filters
   * @return filters
  **/
  @jakarta.annotation.Nullable
  public GroupReconciliationFilters getFilters() {
    return filters;
  }


  public void setFilters(GroupReconciliationFilters filters) {
    this.filters = filters;
  }


  public MatchingRuleset coreRules(List<CoreMatchingRule> coreRules) {
    
    this.coreRules = coreRules;
    return this;
  }

  public MatchingRuleset addCoreRulesItem(CoreMatchingRule coreRulesItem) {
    if (this.coreRules == null) {
      this.coreRules = new ArrayList<>();
    }
    this.coreRules.add(coreRulesItem);
    return this;
  }

   /**
   * The core comparison rules evaluated as derivation formulae against each side of the reconciliation.
   * @return coreRules
  **/
  @jakarta.annotation.Nonnull
  public List<CoreMatchingRule> getCoreRules() {
    return coreRules;
  }


  public void setCoreRules(List<CoreMatchingRule> coreRules) {
    this.coreRules = coreRules;
  }


  public MatchingRuleset aggregateRules(List<AggregateMatchingRule> aggregateRules) {
    
    this.aggregateRules = aggregateRules;
    return this;
  }

  public MatchingRuleset addAggregateRulesItem(AggregateMatchingRule aggregateRulesItem) {
    if (this.aggregateRules == null) {
      this.aggregateRules = new ArrayList<>();
    }
    this.aggregateRules.add(aggregateRulesItem);
    return this;
  }

   /**
   * The aggregate comparison rules evaluated as derivation formulae against values on each side of the reconciliation and operation to aggregate those values.
   * @return aggregateRules
  **/
  @jakarta.annotation.Nonnull
  public List<AggregateMatchingRule> getAggregateRules() {
    return aggregateRules;
  }


  public void setAggregateRules(List<AggregateMatchingRule> aggregateRules) {
    this.aggregateRules = aggregateRules;
  }


  public MatchingRuleset coreTolerances(List<ToleranceBase> coreTolerances) {
    
    this.coreTolerances = coreTolerances;
    return this;
  }

  public MatchingRuleset addCoreTolerancesItem(ToleranceBase coreTolerancesItem) {
    if (this.coreTolerances == null) {
      this.coreTolerances = new ArrayList<>();
    }
    this.coreTolerances.add(coreTolerancesItem);
    return this;
  }

   /**
   * Tolerance configurations applied to core rule matching, in the specified order.
   * @return coreTolerances
  **/
  @jakarta.annotation.Nullable
  public List<ToleranceBase> getCoreTolerances() {
    return coreTolerances;
  }


  public void setCoreTolerances(List<ToleranceBase> coreTolerances) {
    this.coreTolerances = coreTolerances;
  }


  public MatchingRuleset aggregateTolerances(List<ToleranceBase> aggregateTolerances) {
    
    this.aggregateTolerances = aggregateTolerances;
    return this;
  }

  public MatchingRuleset addAggregateTolerancesItem(ToleranceBase aggregateTolerancesItem) {
    if (this.aggregateTolerances == null) {
      this.aggregateTolerances = new ArrayList<>();
    }
    this.aggregateTolerances.add(aggregateTolerancesItem);
    return this;
  }

   /**
   * Tolerance configurations applied to aggregate rule matching.
   * @return aggregateTolerances
  **/
  @jakarta.annotation.Nullable
  public List<ToleranceBase> getAggregateTolerances() {
    return aggregateTolerances;
  }


  public void setAggregateTolerances(List<ToleranceBase> aggregateTolerances) {
    this.aggregateTolerances = aggregateTolerances;
  }


  public MatchingRuleset allowPartialMatching(Boolean allowPartialMatching) {
    
    this.allowPartialMatching = allowPartialMatching;
    return this;
  }

   /**
   * Whether to permit partial matches when applying rules.
   * @return allowPartialMatching
  **/
  @jakarta.annotation.Nullable
  public Boolean getAllowPartialMatching() {
    return allowPartialMatching;
  }


  public void setAllowPartialMatching(Boolean allowPartialMatching) {
    this.allowPartialMatching = allowPartialMatching;
  }


  public MatchingRuleset supplementalAttributes(List<SupplementalAttribute> supplementalAttributes) {
    
    this.supplementalAttributes = supplementalAttributes;
    return this;
  }

  public MatchingRuleset addSupplementalAttributesItem(SupplementalAttribute supplementalAttributesItem) {
    if (this.supplementalAttributes == null) {
      this.supplementalAttributes = new ArrayList<>();
    }
    this.supplementalAttributes.add(supplementalAttributesItem);
    return this;
  }

   /**
   * Supplemental attributes that decorate reconciliation results with additional values without participating in the reconciliation itself.
   * @return supplementalAttributes
  **/
  @jakarta.annotation.Nullable
  public List<SupplementalAttribute> getSupplementalAttributes() {
    return supplementalAttributes;
  }


  public void setSupplementalAttributes(List<SupplementalAttribute> supplementalAttributes) {
    this.supplementalAttributes = supplementalAttributes;
  }


  public MatchingRuleset href(URI href) {
    
    this.href = href;
    return this;
  }

   /**
   * The specific Uniform Resource Identifier (URI) for this resource at the requested effective and asAt datetime.
   * @return href
  **/
  @jakarta.annotation.Nullable
  public URI getHref() {
    return href;
  }


  public void setHref(URI href) {
    this.href = href;
  }


  public MatchingRuleset version(Version version) {
    
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @jakarta.annotation.Nullable
  public Version getVersion() {
    return version;
  }


  public void setVersion(Version version) {
    this.version = version;
  }


  public MatchingRuleset links(List<Link> links) {
    
    this.links = links;
    return this;
  }

  public MatchingRuleset addLinksItem(Link linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<>();
    }
    this.links.add(linksItem);
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @jakarta.annotation.Nullable
  public List<Link> getLinks() {
    return links;
  }


  public void setLinks(List<Link> links) {
    this.links = links;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MatchingRuleset matchingRuleset = (MatchingRuleset) o;
    return Objects.equals(this.id, matchingRuleset.id) &&
        Objects.equals(this.displayName, matchingRuleset.displayName) &&
        Objects.equals(this.recType, matchingRuleset.recType) &&
        Objects.equals(this.datasetSchemas, matchingRuleset.datasetSchemas) &&
        Objects.equals(this.filters, matchingRuleset.filters) &&
        Objects.equals(this.coreRules, matchingRuleset.coreRules) &&
        Objects.equals(this.aggregateRules, matchingRuleset.aggregateRules) &&
        Objects.equals(this.coreTolerances, matchingRuleset.coreTolerances) &&
        Objects.equals(this.aggregateTolerances, matchingRuleset.aggregateTolerances) &&
        Objects.equals(this.allowPartialMatching, matchingRuleset.allowPartialMatching) &&
        Objects.equals(this.supplementalAttributes, matchingRuleset.supplementalAttributes) &&
        Objects.equals(this.href, matchingRuleset.href) &&
        Objects.equals(this.version, matchingRuleset.version) &&
        Objects.equals(this.links, matchingRuleset.links);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, displayName, recType, datasetSchemas, filters, coreRules, aggregateRules, coreTolerances, aggregateTolerances, allowPartialMatching, supplementalAttributes, href, version, links);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MatchingRuleset {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    recType: ").append(toIndentedString(recType)).append("\n");
    sb.append("    datasetSchemas: ").append(toIndentedString(datasetSchemas)).append("\n");
    sb.append("    filters: ").append(toIndentedString(filters)).append("\n");
    sb.append("    coreRules: ").append(toIndentedString(coreRules)).append("\n");
    sb.append("    aggregateRules: ").append(toIndentedString(aggregateRules)).append("\n");
    sb.append("    coreTolerances: ").append(toIndentedString(coreTolerances)).append("\n");
    sb.append("    aggregateTolerances: ").append(toIndentedString(aggregateTolerances)).append("\n");
    sb.append("    allowPartialMatching: ").append(toIndentedString(allowPartialMatching)).append("\n");
    sb.append("    supplementalAttributes: ").append(toIndentedString(supplementalAttributes)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("displayName");
    openapiFields.add("recType");
    openapiFields.add("datasetSchemas");
    openapiFields.add("filters");
    openapiFields.add("coreRules");
    openapiFields.add("aggregateRules");
    openapiFields.add("coreTolerances");
    openapiFields.add("aggregateTolerances");
    openapiFields.add("allowPartialMatching");
    openapiFields.add("supplementalAttributes");
    openapiFields.add("href");
    openapiFields.add("version");
    openapiFields.add("links");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("id");
    openapiRequiredFields.add("displayName");
    openapiRequiredFields.add("recType");
    openapiRequiredFields.add("datasetSchemas");
    openapiRequiredFields.add("coreRules");
    openapiRequiredFields.add("aggregateRules");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to MatchingRuleset
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MatchingRuleset.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in MatchingRuleset is not found in the empty JSON string", MatchingRuleset.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : MatchingRuleset.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `id`
      ResourceId.validateJsonElement(jsonObj.get("id"));
      if (!jsonObj.get("displayName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `displayName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("displayName").toString()));
      }
      if (!jsonObj.get("recType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `recType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("recType").toString()));
      }
      // validate the required field `datasetSchemas`
      RecDatasetSchemas.validateJsonElement(jsonObj.get("datasetSchemas"));
      // validate the optional field `filters`
      if (jsonObj.get("filters") != null && !jsonObj.get("filters").isJsonNull()) {
        GroupReconciliationFilters.validateJsonElement(jsonObj.get("filters"));
      }
      // ensure the json data is an array
      if (!jsonObj.get("coreRules").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `coreRules` to be an array in the JSON string but got `%s`", jsonObj.get("coreRules").toString()));
      }

      JsonArray jsonArraycoreRules = jsonObj.getAsJsonArray("coreRules");
      // validate the required field `coreRules` (array)
      for (int i = 0; i < jsonArraycoreRules.size(); i++) {
        CoreMatchingRule.validateJsonElement(jsonArraycoreRules.get(i));
      };
      // ensure the json data is an array
      if (!jsonObj.get("aggregateRules").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `aggregateRules` to be an array in the JSON string but got `%s`", jsonObj.get("aggregateRules").toString()));
      }

      JsonArray jsonArrayaggregateRules = jsonObj.getAsJsonArray("aggregateRules");
      // validate the required field `aggregateRules` (array)
      for (int i = 0; i < jsonArrayaggregateRules.size(); i++) {
        AggregateMatchingRule.validateJsonElement(jsonArrayaggregateRules.get(i));
      };
      if (jsonObj.get("coreTolerances") != null && !jsonObj.get("coreTolerances").isJsonNull()) {
        JsonArray jsonArraycoreTolerances = jsonObj.getAsJsonArray("coreTolerances");
        if (jsonArraycoreTolerances != null) {
          // ensure the json data is an array
          if (!jsonObj.get("coreTolerances").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `coreTolerances` to be an array in the JSON string but got `%s`", jsonObj.get("coreTolerances").toString()));
          }

          // validate the optional field `coreTolerances` (array)
          for (int i = 0; i < jsonArraycoreTolerances.size(); i++) {
            ToleranceBase.validateJsonElement(jsonArraycoreTolerances.get(i));
          };
        }
      }
      if (jsonObj.get("aggregateTolerances") != null && !jsonObj.get("aggregateTolerances").isJsonNull()) {
        JsonArray jsonArrayaggregateTolerances = jsonObj.getAsJsonArray("aggregateTolerances");
        if (jsonArrayaggregateTolerances != null) {
          // ensure the json data is an array
          if (!jsonObj.get("aggregateTolerances").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `aggregateTolerances` to be an array in the JSON string but got `%s`", jsonObj.get("aggregateTolerances").toString()));
          }

          // validate the optional field `aggregateTolerances` (array)
          for (int i = 0; i < jsonArrayaggregateTolerances.size(); i++) {
            ToleranceBase.validateJsonElement(jsonArrayaggregateTolerances.get(i));
          };
        }
      }
      if (jsonObj.get("supplementalAttributes") != null && !jsonObj.get("supplementalAttributes").isJsonNull()) {
        JsonArray jsonArraysupplementalAttributes = jsonObj.getAsJsonArray("supplementalAttributes");
        if (jsonArraysupplementalAttributes != null) {
          // ensure the json data is an array
          if (!jsonObj.get("supplementalAttributes").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `supplementalAttributes` to be an array in the JSON string but got `%s`", jsonObj.get("supplementalAttributes").toString()));
          }

          // validate the optional field `supplementalAttributes` (array)
          for (int i = 0; i < jsonArraysupplementalAttributes.size(); i++) {
            SupplementalAttribute.validateJsonElement(jsonArraysupplementalAttributes.get(i));
          };
        }
      }
      if ((jsonObj.get("href") != null && !jsonObj.get("href").isJsonNull()) && !jsonObj.get("href").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `href` to be a primitive type in the JSON string but got `%s`", jsonObj.get("href").toString()));
      }
      // validate the optional field `version`
      if (jsonObj.get("version") != null && !jsonObj.get("version").isJsonNull()) {
        Version.validateJsonElement(jsonObj.get("version"));
      }
      if (jsonObj.get("links") != null && !jsonObj.get("links").isJsonNull()) {
        JsonArray jsonArraylinks = jsonObj.getAsJsonArray("links");
        if (jsonArraylinks != null) {
          // ensure the json data is an array
          if (!jsonObj.get("links").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `links` to be an array in the JSON string but got `%s`", jsonObj.get("links").toString()));
          }

          // validate the optional field `links` (array)
          for (int i = 0; i < jsonArraylinks.size(); i++) {
            Link.validateJsonElement(jsonArraylinks.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MatchingRuleset.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MatchingRuleset' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MatchingRuleset> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MatchingRuleset.class));

       return (TypeAdapter<T>) new TypeAdapter<MatchingRuleset>() {
           @Override
           public void write(JsonWriter out, MatchingRuleset value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MatchingRuleset read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of MatchingRuleset given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of MatchingRuleset
  * @throws IOException if the JSON string is invalid with respect to MatchingRuleset
  */
  public static MatchingRuleset fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MatchingRuleset.class);
  }

 /**
  * Convert an instance of MatchingRuleset to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
