/*
 * LUSID API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.lusid.model;

import java.util.Objects;
import com.finbourne.lusid.model.MetadataFieldDefinition;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.lusid.JSON;

/**
 * MetadataFieldsToUpdate
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class MetadataFieldsToUpdate {
  public static final String SERIALIZED_NAME_METADATA_FIELDS = "metadataFields";
  @SerializedName(SERIALIZED_NAME_METADATA_FIELDS)
  private List<MetadataFieldDefinition> metadataFields;

  public MetadataFieldsToUpdate() {
  }

  public MetadataFieldsToUpdate metadataFields(List<MetadataFieldDefinition> metadataFields) {
    
    this.metadataFields = metadataFields;
    return this;
  }

  public MetadataFieldsToUpdate addMetadataFieldsItem(MetadataFieldDefinition metadataFieldsItem) {
    if (this.metadataFields == null) {
      this.metadataFields = new ArrayList<>();
    }
    this.metadataFields.add(metadataFieldsItem);
    return this;
  }

   /**
   * The metadata field definitions for this configuration.
   * @return metadataFields
  **/
  @jakarta.annotation.Nullable
  public List<MetadataFieldDefinition> getMetadataFields() {
    return metadataFields;
  }


  public void setMetadataFields(List<MetadataFieldDefinition> metadataFields) {
    this.metadataFields = metadataFields;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MetadataFieldsToUpdate metadataFieldsToUpdate = (MetadataFieldsToUpdate) o;
    return Objects.equals(this.metadataFields, metadataFieldsToUpdate.metadataFields);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(metadataFields);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MetadataFieldsToUpdate {\n");
    sb.append("    metadataFields: ").append(toIndentedString(metadataFields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("metadataFields");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to MetadataFieldsToUpdate
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MetadataFieldsToUpdate.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in MetadataFieldsToUpdate is not found in the empty JSON string", MetadataFieldsToUpdate.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("metadataFields") != null && !jsonObj.get("metadataFields").isJsonNull()) {
        JsonArray jsonArraymetadataFields = jsonObj.getAsJsonArray("metadataFields");
        if (jsonArraymetadataFields != null) {
          // ensure the json data is an array
          if (!jsonObj.get("metadataFields").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `metadataFields` to be an array in the JSON string but got `%s`", jsonObj.get("metadataFields").toString()));
          }

          // validate the optional field `metadataFields` (array)
          for (int i = 0; i < jsonArraymetadataFields.size(); i++) {
            MetadataFieldDefinition.validateJsonElement(jsonArraymetadataFields.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MetadataFieldsToUpdate.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MetadataFieldsToUpdate' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MetadataFieldsToUpdate> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MetadataFieldsToUpdate.class));

       return (TypeAdapter<T>) new TypeAdapter<MetadataFieldsToUpdate>() {
           @Override
           public void write(JsonWriter out, MetadataFieldsToUpdate value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MetadataFieldsToUpdate read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of MetadataFieldsToUpdate given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of MetadataFieldsToUpdate
  * @throws IOException if the JSON string is invalid with respect to MetadataFieldsToUpdate
  */
  public static MetadataFieldsToUpdate fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MetadataFieldsToUpdate.class);
  }

 /**
  * Convert an instance of MetadataFieldsToUpdate to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
