/*
 * LUSID API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.lusid.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.lusid.JSON;

/**
 * The group-decision detail carried on every member of a FixAsGroup or ForceMatch decision.
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class RecResultDecisionGroup {
  public static final String SERIALIZED_NAME_GROUP_NUMBER = "groupNumber";
  @SerializedName(SERIALIZED_NAME_GROUP_NUMBER)
  private Integer groupNumber;

  public static final String SERIALIZED_NAME_CORE_RULES_EXCUSED = "coreRulesExcused";
  @SerializedName(SERIALIZED_NAME_CORE_RULES_EXCUSED)
  private List<String> coreRulesExcused;

  public RecResultDecisionGroup() {
  }

  public RecResultDecisionGroup groupNumber(Integer groupNumber) {
    
    this.groupNumber = groupNumber;
    return this;
  }

   /**
   * Server-allocated, monotonic group number, unique within the RecResultSet and never reused.
   * @return groupNumber
  **/
  @jakarta.annotation.Nonnull
  public Integer getGroupNumber() {
    return groupNumber;
  }


  public void setGroupNumber(Integer groupNumber) {
    this.groupNumber = groupNumber;
  }


  public RecResultDecisionGroup coreRulesExcused(List<String> coreRulesExcused) {
    
    this.coreRulesExcused = coreRulesExcused;
    return this;
  }

  public RecResultDecisionGroup addCoreRulesExcusedItem(String coreRulesExcusedItem) {
    if (this.coreRulesExcused == null) {
      this.coreRulesExcused = new ArrayList<>();
    }
    this.coreRulesExcused.add(coreRulesExcusedItem);
    return this;
  }

   /**
   * The ruleNames of the core rules excused by a ForceMatch. Identical on every group member; non-null only for ForceMatch.
   * @return coreRulesExcused
  **/
  @jakarta.annotation.Nullable
  public List<String> getCoreRulesExcused() {
    return coreRulesExcused;
  }


  public void setCoreRulesExcused(List<String> coreRulesExcused) {
    this.coreRulesExcused = coreRulesExcused;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecResultDecisionGroup recResultDecisionGroup = (RecResultDecisionGroup) o;
    return Objects.equals(this.groupNumber, recResultDecisionGroup.groupNumber) &&
        Objects.equals(this.coreRulesExcused, recResultDecisionGroup.coreRulesExcused);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(groupNumber, coreRulesExcused);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecResultDecisionGroup {\n");
    sb.append("    groupNumber: ").append(toIndentedString(groupNumber)).append("\n");
    sb.append("    coreRulesExcused: ").append(toIndentedString(coreRulesExcused)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("groupNumber");
    openapiFields.add("coreRulesExcused");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("groupNumber");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to RecResultDecisionGroup
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RecResultDecisionGroup.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RecResultDecisionGroup is not found in the empty JSON string", RecResultDecisionGroup.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : RecResultDecisionGroup.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("coreRulesExcused") != null && !jsonObj.get("coreRulesExcused").isJsonNull() && !jsonObj.get("coreRulesExcused").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `coreRulesExcused` to be an array in the JSON string but got `%s`", jsonObj.get("coreRulesExcused").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RecResultDecisionGroup.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RecResultDecisionGroup' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RecResultDecisionGroup> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RecResultDecisionGroup.class));

       return (TypeAdapter<T>) new TypeAdapter<RecResultDecisionGroup>() {
           @Override
           public void write(JsonWriter out, RecResultDecisionGroup value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RecResultDecisionGroup read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of RecResultDecisionGroup given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of RecResultDecisionGroup
  * @throws IOException if the JSON string is invalid with respect to RecResultDecisionGroup
  */
  public static RecResultDecisionGroup fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RecResultDecisionGroup.class);
  }

 /**
  * Convert an instance of RecResultDecisionGroup to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
