/*
 * LUSID API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.lusid.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.lusid.JSON;

/**
 * The bounds of the spread tier a net cashflow fell in.
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SwingSpreadTierBounds {
  public static final String SERIALIZED_NAME_LOWER_BOUND_EXCLUSIVE = "lowerBoundExclusive";
  @SerializedName(SERIALIZED_NAME_LOWER_BOUND_EXCLUSIVE)
  private java.math.BigDecimal lowerBoundExclusive;

  public static final String SERIALIZED_NAME_UPPER_BOUND_INCLUSIVE = "upperBoundInclusive";
  @SerializedName(SERIALIZED_NAME_UPPER_BOUND_INCLUSIVE)
  private java.math.BigDecimal upperBoundInclusive;

  public SwingSpreadTierBounds() {
  }

  public SwingSpreadTierBounds lowerBoundExclusive(java.math.BigDecimal lowerBoundExclusive) {
    
    this.lowerBoundExclusive = lowerBoundExclusive;
    return this;
  }

   /**
   * The tier&#39;s lower bound, which the net cashflow was above.
   * @return lowerBoundExclusive
  **/
  @jakarta.annotation.Nonnull
  public java.math.BigDecimal getLowerBoundExclusive() {
    return lowerBoundExclusive;
  }


  public void setLowerBoundExclusive(java.math.BigDecimal lowerBoundExclusive) {
    this.lowerBoundExclusive = lowerBoundExclusive;
  }


  public SwingSpreadTierBounds upperBoundInclusive(java.math.BigDecimal upperBoundInclusive) {
    
    this.upperBoundInclusive = upperBoundInclusive;
    return this;
  }

   /**
   * The tier&#39;s upper bound, which the net cashflow was at or below. Absent for the unbounded last tier.
   * @return upperBoundInclusive
  **/
  @jakarta.annotation.Nullable
  public java.math.BigDecimal getUpperBoundInclusive() {
    return upperBoundInclusive;
  }


  public void setUpperBoundInclusive(java.math.BigDecimal upperBoundInclusive) {
    this.upperBoundInclusive = upperBoundInclusive;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SwingSpreadTierBounds swingSpreadTierBounds = (SwingSpreadTierBounds) o;
    return (this.lowerBoundExclusive.compareTo(swingSpreadTierBounds.getLowerBoundExclusive()) == 0) &&
        (this.upperBoundInclusive.compareTo(swingSpreadTierBounds.getUpperBoundInclusive()) == 0);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(lowerBoundExclusive, upperBoundInclusive);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SwingSpreadTierBounds {\n");
    sb.append("    lowerBoundExclusive: ").append(toIndentedString(lowerBoundExclusive)).append("\n");
    sb.append("    upperBoundInclusive: ").append(toIndentedString(upperBoundInclusive)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("lowerBoundExclusive");
    openapiFields.add("upperBoundInclusive");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("lowerBoundExclusive");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to SwingSpreadTierBounds
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SwingSpreadTierBounds.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SwingSpreadTierBounds is not found in the empty JSON string", SwingSpreadTierBounds.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SwingSpreadTierBounds.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SwingSpreadTierBounds.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SwingSpreadTierBounds' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SwingSpreadTierBounds> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SwingSpreadTierBounds.class));

       return (TypeAdapter<T>) new TypeAdapter<SwingSpreadTierBounds>() {
           @Override
           public void write(JsonWriter out, SwingSpreadTierBounds value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SwingSpreadTierBounds read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SwingSpreadTierBounds given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SwingSpreadTierBounds
  * @throws IOException if the JSON string is invalid with respect to SwingSpreadTierBounds
  */
  public static SwingSpreadTierBounds fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SwingSpreadTierBounds.class);
  }

 /**
  * Convert an instance of SwingSpreadTierBounds to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
