/*
 * LUSID API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.lusid.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.lusid.JSON;

/**
 * One factor of a result&#39;s unit, modelled as dimensional analysis rather than a label, e.g. a  rates delta is GBP^1 . GBP.LIBOR.3M^-1 - \&quot;GBP per basis point\&quot;. A result&#39;s &#x60;units&#x60; is a  flat list of these; the count tracks the order of the derivative (a ratio), not the result&#39;s  axes, and must not be indexed by axis.
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class UnitDimension {
  public static final String SERIALIZED_NAME_UNIT_DOMAIN = "unitDomain";
  @SerializedName(SERIALIZED_NAME_UNIT_DOMAIN)
  private String unitDomain;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_POWER = "power";
  @SerializedName(SERIALIZED_NAME_POWER)
  private Integer power;

  public static final String SERIALIZED_NAME_SCALE = "scale";
  @SerializedName(SERIALIZED_NAME_SCALE)
  private java.math.BigDecimal scale;

  public UnitDimension() {
  }

  public UnitDimension unitDomain(String unitDomain) {
    
    this.unitDomain = unitDomain;
    return this;
  }

   /**
   * The domain this factor is drawn from, e.g. \&quot;Ccy\&quot;, \&quot;Rate\&quot;, \&quot;Vol\&quot;, \&quot;Security\&quot;.
   * @return unitDomain
  **/
  @jakarta.annotation.Nullable
  public String getUnitDomain() {
    return unitDomain;
  }


  public void setUnitDomain(String unitDomain) {
    this.unitDomain = unitDomain;
  }


  public UnitDimension name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name within the domain, e.g. a currency code or a curve identifier.
   * @return name
  **/
  @jakarta.annotation.Nullable
  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public UnitDimension power(Integer power) {
    
    this.power = power;
    return this;
  }

   /**
   * The exponent this factor is raised to.
   * @return power
  **/
  @jakarta.annotation.Nullable
  public Integer getPower() {
    return power;
  }


  public void setPower(Integer power) {
    this.power = power;
  }


  public UnitDimension scale(java.math.BigDecimal scale) {
    
    this.scale = scale;
    return this;
  }

   /**
   * The scale of one unit of this factor, e.g. 1e-4 for a basis point.
   * @return scale
  **/
  @jakarta.annotation.Nullable
  public java.math.BigDecimal getScale() {
    return scale;
  }


  public void setScale(java.math.BigDecimal scale) {
    this.scale = scale;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UnitDimension unitDimension = (UnitDimension) o;
    return Objects.equals(this.unitDomain, unitDimension.unitDomain) &&
        Objects.equals(this.name, unitDimension.name) &&
        Objects.equals(this.power, unitDimension.power) &&
        (this.scale.compareTo(unitDimension.getScale()) == 0);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(unitDomain, name, power, scale);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UnitDimension {\n");
    sb.append("    unitDomain: ").append(toIndentedString(unitDomain)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    power: ").append(toIndentedString(power)).append("\n");
    sb.append("    scale: ").append(toIndentedString(scale)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("unitDomain");
    openapiFields.add("name");
    openapiFields.add("power");
    openapiFields.add("scale");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to UnitDimension
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UnitDimension.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UnitDimension is not found in the empty JSON string", UnitDimension.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("unitDomain") != null && !jsonObj.get("unitDomain").isJsonNull()) && !jsonObj.get("unitDomain").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `unitDomain` to be a primitive type in the JSON string but got `%s`", jsonObj.get("unitDomain").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UnitDimension.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UnitDimension' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UnitDimension> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UnitDimension.class));

       return (TypeAdapter<T>) new TypeAdapter<UnitDimension>() {
           @Override
           public void write(JsonWriter out, UnitDimension value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UnitDimension read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of UnitDimension given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of UnitDimension
  * @throws IOException if the JSON string is invalid with respect to UnitDimension
  */
  public static UnitDimension fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UnitDimension.class);
  }

 /**
  * Convert an instance of UnitDimension to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
